In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/drug.csv")
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [ ]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Drug'].unique()

array(['DrugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [ ]:
df['Drug'].value_counts()

Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [ ]:
#labelencoding


from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
for i in df.columns:
  if df[i].dtype == "object":
    df[i] = le.fit_transform(df[i])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    int64
 2   BP           200 non-null    int64
 3   Cholesterol  200 non-null    int64
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    int64
dtypes: float64(1), int64(5)
memory usage: 9.5 KB

In [ ]:
#Model building

x = df.drop("Drug", axis = 1)
y = df['Drug']

In [ ]:
x

     Age  Sex  BP  Cholesterol  Na_to_K
0     23    0   0            0   25.355
1     47    1   1            0   13.093
2     47    1   1            0   10.114
3     28    0   2            0    7.798
4     61    0   1            0   18.043
..   ...  ...  ..          ...      ...
195   56    0   1            0   11.567
196   16    1   1            0   12.006
197   52    1   2            0    9.894
198   23    1   2            1   14.020
199   40    0   1            1   11.349

[200 rows x 5 columns]

In [ ]:
y

0      0
1      3
2      3
3      4
4      0
      ..
195    3
196    3
197    4
198    4
199    4
Name: Drug, Length: 200, dtype: int64

In [ ]:
#train-test-split

from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.8,random_state =0)

In [ ]:
#svc  --- bydefault - rbf
from sklearn.svm import SVC
model = SVC()
#training
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

#import evalution

from sklearn.metrics import*
print(accuracy_score(y_test,y_pred)*100)

82.5

In [ ]:
#svc  --- bydefault - rbf
from sklearn.svm import SVC
model = SVC(kernel = "rbf")
#training
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

#import evalution

from sklearn.metrics import*
print(accuracy_score(y_test,y_pred)*100)

82.5

In [ ]:
#svc  --- linear
from sklearn.svm import SVC
model = SVC(kernel = "linear")
#training
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

#import evalution

from sklearn.metrics import*
print(accuracy_score(y_test,y_pred)*100)

100.0

In [ ]:
#svc  ---poly
from sklearn.svm import SVC
model = SVC(kernel = "poly")
#training
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

#import evalution

from sklearn.metrics import*
print(accuracy_score(y_test,y_pred)*100)

80.0

In [ ]:
#first to complete this
#what other algo? - lr,dt,rf
#and do let me know the accuracy by 10:10